[package]
name = "ror_launch"
version = "1.0.1"
authors = ["Sammy James <sammy.james@protonmail.com>"]

[dependencies]
log = "*"
simple_logger = "*"
curl = "*"
serde = "*"
serde_derive = "*"
serde-xml-rs = "0.2.1"
bytebuffer = "*"
sha2 = "*"
md-5 = "*"
base64 = "*"
tempfile = "2.2.0"
